### PR TITLE
chinese.lng

### PR DESCRIPTION
**Pull request by xuxugzs**
Finish 100% you can use it

### CODE REVIEW

**Comment by xuxugzs** [comment]
i hope >o<

**Comment by Angelic47** [comment]
Thanks a lot :D 
(非常感谢帮忙汉化=w=~)

**Comment by Angelic47** [comment]
cmd_kickall_no_reason contains a wrong word, which you can edit it.
(cmd_kickall_no_reason有个地方写错了个字)

**Comment by Pub4Game** [comment]
@Angelic47 Translation done correctly? I can add it?

**Comment by Angelic47** [comment]
@Pub4Game It contains some mistakes which not nessesary. U can merge it now, and I will create a new pull request to fix it after merged :D

**Comment by Pub4Game** [comment]
@xuxugzs Thanks again for the translation!

**Pull request merged**
